language: node_js
cache: false
dist: bionic

branches:
  only:
  - master
  - /^release\/.*$/

node_js:
  - 'lts/*'
  - 'node'

stages:
  - check

os:
  - linux
  - osx
  - windows

script: npx aegir test -t node --bail -- --exit

jobs:
  include:
    - stage: check
      script:
        - npx aegir dep-check
        - npm run lint

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script: npx aegir test -t browser -t webworker

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script: npx aegir test -t browser -t webworker -- --browser firefox

notifications:
  email: false
